#include "randfile.h"

int main(){
  // 1. Populates an array with 10 random numbers generated by your random function (print out each value)
  printf("Generating random numbers:\n");
  int nums[10];
  int i = 0;
  for (; i < 10; i++) {
    nums[i] = getRandNum();
    printf("\trandom %d: %d\n", i, nums[i]);
  }

  // 2. Writes the array to a file
  // Do not use a loop when writing to the file
  printf("\nWriting numbers to file...\n");
  int fd = open("random.txt", O_CREAT | O_WRONLY, 0644);
  if (fd == -1) {
    printf("Errno: %s\n", strerror(errno));
  }
  write(fd, nums, sizeof(int) * 10);
  if (errno != 0) {
    printf("Errno: %s\n", strerror(errno));
  }
  close(fd);

  // 3. Reads that file into a different array
  // Do not use a loop when reading from the file
  printf("\nReading numbers from file...\n");
  int newNums[10];
  fd = open("random.txt", O_RDONLY);
  if (fd == -1) {
    printf("Errno: %s\n", strerror(errno));
  }
  read(fd, newNums, sizeof(int) * 10);
  if (errno != 0) {
    printf("Errno: %s\n", strerror(errno));
  }
  close(fd);


  // 4. Prints out the contents of the second array to verify the random numbers are the same from step 1
  printf("\nVerification that written values were the same:\n");
  int x = 0;
  for (; x < 10; x++) {
    printf("\trandom %d: %d\n", x, newNums[x]);
  }

  return 0;
}
