#include "randfile.h"

// A main function that:


// 1. Populates an array with 10 random numbers generated by your random function (print out each value)
// If your program seems to stall at this step, it's possible that your computer doesn't have enough entropy and is waiting, you can read from /dev/urandom instead.


// 2. Writes the array to a file
// Do not use a loop when writing to the file

// 3. Reads that file into a different array
// Do not use a loop when reading from the file


// 4. Prints out the contents of the second array to verify the random numbers are the same from step 1
